name: Build and Publish Tauri App on Deploy PR Merge

on:
  pull_request:
    types: [closed]
    branches:
      - deploy

jobs:
  build-frontend:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Clone fe_invoice
      run: git clone https://github.com/NguyenTrungNghia1996/fe_invoice.git

    - name: Install and build Nuxt
      working-directory: fe_invoice
      run: |
        yarn install
        yarn generate

    - name: Upload frontend artifact
      uses: actions/upload-artifact@v4
      with:
        name: fe_build
        path: fe_invoice/.output/public/

  build-backend:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Clone be_invoice
      run: git clone https://github.com/NguyenTrungNghia1996/be_invoice.git

    - name: Build Go backend for Windows
      working-directory: be_invoice
      run: |
        GOOS=windows GOARCH=amd64 go build -o backend.exe main.go

    - name: Upload backend artifact
      uses: actions/upload-artifact@v4
      with:
        name: backend_binary
        path: be_invoice/backend.exe

  build-tauri:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    needs: [build-frontend, build-backend]

    steps:
    - name: Checkout invoice_desktop repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Setup Yarn
      run: npm install -g yarn

    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Download frontend artifact
      uses: actions/download-artifact@v4
      with:
        name: fe_build
        path: resources/fe

    - name: Download backend artifact
      uses: actions/download-artifact@v4
      with:
        name: backend_binary
        path: resources/bin

    - name: Install Tauri project dependencies
      run: yarn install

    - name: Build Tauri app
      run: yarn tauri build

    - name: Find .msi and .exe installers
      id: find-installers
      run: |
        $files = Get-ChildItem -Recurse -Path src-tauri\target\release\bundle\ -Include *.msi, *.exe | ForEach-Object { $_.FullName }
        $list = $files -join "`n"
        "files<<EOF" >> $env:GITHUB_OUTPUT
        $list >> $env:GITHUB_OUTPUT
        "EOF" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.sha }}
        tag_name: release-${{ github.sha }}
        files: ${{ steps.find-installers.outputs.files }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
